"""add_finca_id_to_tarifas_cliente_producto

Revision ID: 315f25ec649b
Revises: 162e9b18fe89
Create Date: 2026-05-24 19:19:24.523998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315f25ec649b'
down_revision: Union[str, None] = '162e9b18fe89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarifas_cliente_producto', sa.Column('finca_id', sa.Uuid(), nullable=True))
    op.drop_constraint('uq_tarifa_com_cli_prod', 'tarifas_cliente_producto', type_='unique')
    op.create_unique_constraint('uq_tarifa_com_cli_prod_finca', 'tarifas_cliente_producto', ['comisionista_id', 'cliente_id', 'producto_id', 'finca_id'])
    op.create_foreign_key(None, 'tarifas_cliente_producto', 'fincas', ['finca_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tarifas_cliente_producto', type_='foreignkey')
    op.drop_constraint('uq_tarifa_com_cli_prod_finca', 'tarifas_cliente_producto', type_='unique')
    op.create_unique_constraint('uq_tarifa_com_cli_prod', 'tarifas_cliente_producto', ['comisionista_id', 'cliente_id', 'producto_id'])
    op.drop_column('tarifas_cliente_producto', 'finca_id')
    # ### end Alembic commands ###
