"""add_cliente_producto_finca_to_orden_items

Revision ID: 4c97285a3b6c
Revises: 315f25ec649b
Create Date: 2026-05-24 19:32:11.948869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c97285a3b6c'
down_revision: Union[str, None] = '315f25ec649b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liquidacion_items', sa.Column('cliente_snapshot', sa.String(), nullable=True))
    op.add_column('liquidacion_items', sa.Column('retencion_porcentaje_snapshot', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('orden_items', sa.Column('cliente_id', sa.Uuid(), nullable=True))
    op.add_column('orden_items', sa.Column('producto_id', sa.Uuid(), nullable=True))
    op.add_column('orden_items', sa.Column('finca_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'orden_items', 'productos', ['producto_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orden_items', 'fincas', ['finca_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orden_items', 'clientes', ['cliente_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orden_items', type_='foreignkey')
    op.drop_constraint(None, 'orden_items', type_='foreignkey')
    op.drop_constraint(None, 'orden_items', type_='foreignkey')
    op.drop_column('orden_items', 'finca_id')
    op.drop_column('orden_items', 'producto_id')
    op.drop_column('orden_items', 'cliente_id')
    op.drop_column('liquidacion_items', 'retencion_porcentaje_snapshot')
    op.drop_column('liquidacion_items', 'cliente_snapshot')
    # ### end Alembic commands ###
