"""add_proveedores_excluidos_to_tarifas

Revision ID: 58e774dfe64f
Revises: a9ebb296c1bc
Create Date: 2026-06-05 10:24:51.621017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e774dfe64f'
down_revision: Union[str, None] = 'a9ebb296c1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarifas', sa.Column('proveedores_excluidos', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarifas', 'proveedores_excluidos')
    # ### end Alembic commands ###
