"""add_peso_por_unidad_to_productos

Revision ID: 991bbe37b7ef
Revises: f4e8a2c1d3b0
Create Date: 2026-06-03 15:08:59.459194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991bbe37b7ef'
down_revision: Union[str, None] = 'f4e8a2c1d3b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('peso_por_unidad', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'peso_por_unidad')
    # ### end Alembic commands ###
