"""add_proveedores_excluidos_to_tarifas_cliente_producto

Revision ID: a13231cb642e
Revises: 58e774dfe64f
Create Date: 2026-06-05 10:38:04.849469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a13231cb642e'
down_revision: Union[str, None] = '58e774dfe64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarifas_cliente_producto', sa.Column('proveedores_excluidos', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarifas_cliente_producto', 'proveedores_excluidos')
    # ### end Alembic commands ###
