"""add_proveedor_to_tarifas_cliente_producto

Revision ID: a9ebb296c1bc
Revises: f76353be2851
Create Date: 2026-06-05 07:35:30.496942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ebb296c1bc'
down_revision: Union[str, None] = 'f76353be2851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarifas_cliente_producto', sa.Column('proveedor', sa.String(), nullable=False, server_default=''))
    op.drop_constraint('uq_tarifa_com_cli_prod_finca', 'tarifas_cliente_producto', type_='unique')
    op.create_unique_constraint('uq_tarifa_com_cli_prod_finca_prov', 'tarifas_cliente_producto', ['comisionista_id', 'cliente_id', 'producto_id', 'finca_id', 'proveedor'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tarifa_com_cli_prod_finca_prov', 'tarifas_cliente_producto', type_='unique')
    op.create_unique_constraint('uq_tarifa_com_cli_prod_finca', 'tarifas_cliente_producto', ['comisionista_id', 'cliente_id', 'producto_id', 'finca_id'])
    op.drop_column('tarifas_cliente_producto', 'proveedor')
    # ### end Alembic commands ###
