"""add_clientes_fincas_productos

Revision ID: b51c1050e77a
Revises: 
Create Date: 2026-05-24 19:01:32.448988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51c1050e77a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('retencion_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('productos',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('unidad_comision', sa.String(length=20), nullable=False),
    sa.Column('tacho_kilos', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('fincas',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'nombre', name='uq_finca_cliente_nombre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fincas')
    op.drop_table('productos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
