"""crear tabla proveedores con seed

Revision ID: b7494b241946
Revises: a13231cb642e
Create Date: 2026-06-05 11:00:10.354266

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column


# revision identifiers, used by Alembic.
revision: str = 'b7494b241946'
down_revision: Union[str, None] = 'a13231cb642e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###

    proveedores_table = table('proveedores', column('id', sa.UUID), column('nombre', sa.String))
    op.bulk_insert(proveedores_table, [
        {'id': str(uuid.uuid4()), 'nombre': 'MALAVE JIMENEZ LUIS ALFREDO'},
        {'id': str(uuid.uuid4()), 'nombre': 'BIOFORCE AVICOLA'},
        {'id': str(uuid.uuid4()), 'nombre': 'OCHOA RECALDE ELIZABETH MERCEDES'},
        {'id': str(uuid.uuid4()), 'nombre': 'INDUSTRIAL ACUICOLA OCHOA & BARCIA DINACUAMAR CIA.LTDA.'},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proveedores')
    # ### end Alembic commands ###
