"""add_saco_kilos_to_productos

Revision ID: f76353be2851
Revises: 10bb78dc763d
Create Date: 2026-06-03 19:03:00.458317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76353be2851'
down_revision: Union[str, None] = '10bb78dc763d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('saco_kilos', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'saco_kilos')
    # ### end Alembic commands ###
